version: '3.5'
services:
  vault-agent:
    image: "vault:latest"
    container_name: vault-agent
    volumes:
      - /home/dnabiev/vault-docker/agent:/vault/config:rw
      - /home/dnabiev/vault-docker/agent:/var/log/vault:rw
    cap_add:
    - IPC_LOCK
    entrypoint: vault agent -config=/vault/config/agent.conf 
    networks:
      net1:
          aliases:
            - vault-agent  
networks:
  net1:
    name: test
      